version: "3.9"

services:
  mongodb:
    container_name: copy-mongo
    image: ${REGISTRY_URL}/${USER_NAME}/copy-mongo
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64/v8        # linux/amd64 / linux/arm64/v8
    restart: "no"
    working_dir: /app
    env_file:
      - .env
    environment:
      - DB_NAME=${DB_NAME:-test}
      - DB_USER=${DB_USER:-root}
      - DB_PASS=${DB_PASS:-toor}
    ports:
      - "${PORT:-27017}:27017"      # host:container
    volumes:
      # - .:/app
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    logging:
      options:
        max-size: 1g

volumes:
  mongodb:
  mongodb_config:
