version: "3.9"

services:
  mongodb:
    container_name: mongodb-7.0.4-jammy
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64         # linux/amd64 / linux/arm64/v8
    restart: "no"
    working_dir: /app
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS:-root}
    ports:
      - ${PORT:-27017}:27017      # host:container
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    logging:
      options:
          max-size: 1g
