version: "3.9"

services:
  mongodb:
    container_name: mongodb-7.0.4
    image: mongo:7.0.4-jammy
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    platform: linux/arm64/v8      # linux/amd64 / linux/arm64/v8
    restart: "no"
    working_dir: /app
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME:-test}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS:-toor}
    ports:
      - "27017:27017"             # host:container
    volumes:
      - .:/app
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    logging:
      options:
        max-size: 1g
    command: ["./entrypoint.sh"]

volumes:
  mongodb:
  mongodb_config:
