name: Automerge

on:
  # push:
  #   branches:
  #     - main
  #     - release-please--branches--main

  schedule:
    - cron: 0 * * * *

  pull_request_review:
    types:
      - submitted

  pull_request_target:
    branches:
      - main
      - release-please--branches--main
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review

  workflow_dispatch:
    inputs:
      pull-request:
        description: Pull Request Number
        required: false
      review:
        description: Review ID
        required: false

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          token: "${{ secrets.AUTOMERGE_PAT }}"
          merge-method: rebase
          do-not-merge-labels: never-merge
          required-labels: "autorelease: pending"
          pull-request: "${{ github.event.inputs.pull-request }}"
          review: "${{ github.event.inputs.review }}"
          dry-run: true
